name: Build QMK Firmware

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install QMK dependencies
        run: |
          sudo apt update
          sudo apt install -y git python3-pip dfu-util gcc-avr binutils-avr gdb-avr avr-libc \
            gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi
          python3 -m pip install --upgrade pip
          pip3 install qmk

      - name: Setup QMK
        run: qmk setup -y

      - name: Copy keyboard into QMK tree
        run: |
          mkdir -p ~/qmk_firmware/keyboards/al68
          cp -r ./al68/* ~/qmk_firmware/keyboards/al68/

      - name: Compile firmware
        run: |
          cd ~/qmk_firmware
          qmk compile -kb al68 -km default

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v3
        with:
          name: al68_firmware
          path: ~/qmk_firmware/*.hex
